const CREATE_ROOM = 'game/CREATE_ROOM'
const JOIN_ROOM = 'game/JOIN_ROOM'
const JOINING_ROOM_NOT_EXIST = 'game/JOINING_ROOM_NOT_EXIST'
const ROOM_CHANGE = 'game/ROOM_CHANGE'
const ROOM_PLAYERS_CHANGE = 'game/ROOM_PLAYERS_CHANGE'
const LEAVE_ROOM = 'game/LEAVE_ROOM'

export default {
  CREATE_ROOM,
  JOIN_ROOM,
  JOINING_ROOM_NOT_EXIST,
  ROOM_CHANGE,
  ROOM_PLAYERS_CHANGE,
  LEAVE_ROOM
}
