const AUTH_STATE_CHANGE = 'session/AUTH_STATE_CHANGE'
const REQUEST_FB_SIGN_IN = 'session/REQUEST_FB_SIGN_IN'
const SIGN_OUT = 'session/SIGN_OUT'

export default {
  AUTH_STATE_CHANGE,
  REQUEST_FB_SIGN_IN,
  SIGN_OUT
}
